version: "3"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: shop_postgres
    ports:
      - "${POSTGRES_PORT:-8534}:5433"
    volumes:
      - "./docker/postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

  pgAdmin:
    image: dpage/pgadmin4:8.5
    container_name: shop_pgadmin
    ports:
      - "10000:80"
    volumes:
      - "./docker/pgadmin-config/servers.json:/servers/servers.json"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_SERVER_JSON_FILE=/servers/servers.json


volumes:
  progresDB: